PRIVMSG #CHANNEL_NAME :OWNER: Usage: markov <word>
PRIVMSG #CHANNEL_NAME :OWNER: thing
PRIVMSG #CHANNEL_NAME :OWNER: two things
PRIVMSG #CHANNEL_NAME :OWNER: thing two three
PRIVMSG #CHANNEL_NAME :OWNER: thing two
PRIVMSG #CHANNEL_NAME :OWNER: thing two three
PRIVMSG #CHANNEL_NAME :OWNER: thing two three
PRIVMSG #CHANNEL_NAME :OWNER: thing one
PRIVMSG OWNER :Dumped 13 markov chain entries
